### ISSUE TITLE
Gravity PDF Installation Problem

### ISSUE THREAD

**Issue by camphi** [DigitalPygmalion/badge-factor-boilerplate#3]
Gravity PDF Installation Problem
The minimum requirements for Gravity PDF have not been met. Please fix the issue(s) below to continue:
Gravity Forms Version 1.9 is required. Get more info.
The PHP Extension MB String could not be detected. Contact your web hosting provider to fix. Get more info.
The PHP Extension GD Image Library could not be detected. Contact your web hosting provider to fix. Get more info.

**Comment by danidou** [comment]
The installation instructions require the installation of Gravity Forms prior to the activation of all other plugins.  I've added the specification of the minimum version (1.9) in the instructions to avoid this problem.
